name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - user/adutt2/updatedsite  # Change to your default branch if needed  # Change to your default branch if needed

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.2' # Updated to meet bundler requirement

      # - name: Install Bundler 2.7.2
      #   run: gem install bundler -v 2.7.2

      # - name: Install dependencies
      #   run: bundle _2.7.2_ install

      # - name: Build Jekyll site
      #   run: bundle exec jekyll build

      # - name: Upload artifact for deployment
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build
      #     path: _site

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "/"      # Location of your application source code
          output_location: "_site" # Built static files location
      - name: Convert HTML to JSON
        run: |
          npm install cheerio
          node assets/js/html-to-json.js
      - name: Upload site to Azure Blob Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
              --destination 'docs-site' \
              --source ./converted-json \
              --auth-mode key \
              --account-key ${{ secrets.AZURE_STORAGE_KEY }}
